name: Format

on:
  push:
    branches:
      - master
    paths:
      - 'tools/templates/manifest.json'

jobs:
  format-code:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Checkout Ref
        uses: actions/checkout@v4

      - name: Restore NPM Cached Files
        uses: actions/cache@v4
        id: npm-cache
        with:
          path: |
            ~/.npm
            ./tools/node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('./tools/package-lock.json') }}
          restore-keys: ${{ runner.os }}-npm-

      - name: Setup NodeJS v20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          check-latest: true

      - name: Setup NPM Packages
        if: steps.npm-cache.outputs.cache-hit != 'true'
        working-directory: ./tools
        run: npm ci

      - name: Sync Manifest
        run: npm run sync-manifest

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'sync manifest.json from template'
          file_pattern: 'tools/templates/manifest.json'
          author_name: 'hog-management[bot] <1048098+hog-management[bot]@users.noreply.github.com>'
          author_user_name: 'hog-management[bot]'
          author_email: '1048098+hog-management[bot]@users.noreply.github.com'
          branch: master