name: Test Commit Syntax

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - test-buildscript*

jobs:
  testCommits:
    if: "${{ github.repository_owner == 'Horde-Of-Greg' }}"
    name: Test Commits
    uses: ./.github/workflows/createchangelog.yml
    with:
      release_type: "Cutting Edge Build"
      test: true
    secrets: inherit
